config/routes.rb
BlacklightOaiHarvesterDemo::Application.routes.draw do
  Blacklight.add_routes(self)

  root :to => "catalog#index"

  devise_for :users

  resources :providers

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  validates :endpoint_url, :presence => true, :format => { :with => /^https?/, :message => "must be an http/https url"}

  before_save do
    self.name = nil if self.name.blank?
    self.set = nil if self.set.blank?
    self.metadata_prefix = nil if self.metadata_prefix.blank?
  end

  def client
    OAI::Client.new(self.endpoint_url, :parser => 'libxml')
  end

  def granularity
    client.identify.granularity
  end

  def each_record(options = {}, &block)
    response = nil
    count = 0

    begin
      local_options = {}
      local_options[:resumption_token] = response.resumption_token if response and response.resumption_token and not response.resumption_token.empty?
      local_options = oai_client_options if local_options.empty?

      response = client.list_records(local_options)

      response.doc.find("/OAI-PMH/ListRecords/record").each do |record|
        count += 1 

        yield record

        break if options[:limit] and count >= options[:limit]
      end
      

    rescue
      raise unless $!.respond_to?(:code) and $!.try(:code) ==  "noRecordsMatch"
    end while (options[:limit].blank? or count < options[:limit]) and not response.try(:resumption_token).blank?
  end

  def consume!(options = {})
    count = 0

    each_record(options) do |xml|
      process_record(xml)
      count += 1
    end

    self.consumed_at = Time.now
    save

    count
  end

  def name
    read_attribute(:name) || endpoint_url
  end

  def metadata_prefix
    read_attribute(:metadata_prefix) || 'oai_dc'
  end

  def next_harvest_at
    consumed_at + interval
  end

  def consumed_at
    read_attribute(:consumed_at) || Time.at(1)
  end

  def interval
    (read_attribute(:interval) || 1.day).seconds
  end

  def record_class
    str = read_attribute(:record_class) || default_record_class_name
    str.camelcase.constantize
  rescue 
    nil
  end

  def default_record_class_name
    "#{metadata_prefix}_document"
  end

  def record_class= klass
    self[:record_class] = klass.to_s
  end

  protected
  def oai_client_options
    options = {}
    options[:set] = set unless set.blank?
    options[:from] = consumed_at.utc.xmlschema.to_s.slice(0,granularity.length) unless consumed_at.blank?
    options[:metadata_prefix] = metadata_prefix

    options
  end

  def process_record xml
    record = record_class.from_xml xml.to_s
    record.provider = self
    record.update_index
    record
  end

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @providers }
    end
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
    @provider = Provider.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @provider }
    end
  end

  # GET /providers/new
  # GET /providers/new.json
  def new
    @provider = Provider.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @provider }
    end
  end

  # GET /providers/1/edit
  def edit
    @provider = Provider.find(params[:id])
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(params[:provider])

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, :notice => 'Provider was successfully created.' }
        format.json { render :json => @provider, :status => :created, :location => @provider }
      else
        format.html { render :action => "new" }
        format.json { render :json => @provider.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /providers/1
  # PUT /providers/1.json
  def update
    @provider = Provider.find(params[:id])

    respond_to do |format|
      if @provider.update_attributes(params[:provider])
        format.html { redirect_to @provider, :notice => 'Provider was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @provider.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider = Provider.find(params[:id])
    @provider.destroy

    respond_to do |format|
      format.html { redirect_to providers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :endpoint_url %><br />
    <%= f.text_field :endpoint_url %>
  </div>
  <div class="field">
    <%= f.label :metadata_prefix %><br />
    <%= f.text_field :metadata_prefix %>
  </div>
  <div class="field">
    <%= f.label :set %><br />
    <%= f.text_field :set %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<h1>Listing providers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Endpoint url</th>
    <th>Metadata prefix</th>
    <th>Set</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @providers.each do |provider| %>
  <tr>
    <td><%= provider.name %></td>
    <td><%= provider.description %></td>
    <td><%= provider.endpoint_url %></td>
    <td><%= provider.metadata_prefix %></td>
    <td><%= provider.set %></td>
    <td><%= link_to 'Show', provider %></td>
    <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
    <td><%= link_to 'Destroy', provider, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Provider', new_provider_path %>

app/views/providers/new.html.erb
<h1>New provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @provider.name %>
</p>

<p>
  <b>Description:</b>
  <%= @provider.description %>
</p>

<p>
  <b>Endpoint url:</b>
  <%= @provider.endpoint_url %>
</p>

<p>
  <b>Metadata prefix:</b>
  <%= @provider.metadata_prefix %>
</p>

<p>
  <b>Set:</b>
  <%= @provider.set %>
</p>

<p>
  <b><%= link_to "Records", catalog_index_path(:f => { :provider_id_i => @provider.id }) %></b>
</p>




<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>